services:
  - type: web
    name: logistics-backend-wv0x
    env: python
    rootDir: backend
    region: ohio
    plan: starter
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    disk:
      name: sqlite-data
      mountPath: /data
      sizeGB: 1
    envVars:
      - key: DB_PATH
        value: "/data/database.db"
      - key: PYTHON_VERSION
        value: "3.11.9"
